name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v1
        - run: bun install
        - run: bun run test
        - run: bun run build
        - name: go-semantic-release
          id: semrel
          uses: ./
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Set up Git
          if: steps.semrel.outputs.version != ''
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        - name: Update major tag
          if: steps.semrel.outputs.version != ''
          run: |
            TAG=v${{ steps.semrel.outputs.version_major }}
            git push origin :refs/tags/${TAG}
            git tag -fa ${TAG} -m "Release v${{ steps.semrel.outputs.version }}"
            git push origin ${TAG}
        - name: Update minor tag
          if: steps.semrel.outputs.version != ''
          run: |
            TAG=v${{ steps.semrel.outputs.version_major }}.${{ steps.semrel.outputs.version_minor }}
            git push origin :refs/tags/${TAG}
            git tag -fa ${TAG} -m "Release v${{ steps.semrel.outputs.version }}"
            git push origin ${TAG}
