name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12.x
        - run: npm ci
        - run: npm test
        - run: npm run build
        - uses: ./
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
